version: '3.4'

services:
  php:
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - .:/var/www/html
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8232:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

